# Generated by Django 5.0.6 on 2025-06-06 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha_entrega', models.DateField()),
                ('estado', models.CharField(default='pendiente', max_length=50)),
                ('precio_total', models.IntegerField()),
            ],
        ),
    ]
