# Generated by Django 5.0.6 on 2025-06-26 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_cantidad_alter_pedido_precio_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_plan', models.CharField(choices=[('MENSUAL', 'Plan Mensual'), ('TRIMESTRAL', 'Plan Trimestral'), ('ANUAL', 'Plan Anual')], max_length=15)),
                ('frecuencia_entrega', models.PositiveIntegerField(help_text='Cantidad de bidones por mes')),
                ('incluye_dispensador', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='planes/')),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('tipo_producto', models.CharField(choices=[('BIDON', 'Bidón de Agua'), ('DISPENSADOR', 'Dispensador'), ('ACCESORIO', 'Accesorio')], max_length=20)),
                ('tipo_bidon', models.CharField(blank=True, choices=[('5L', 'Bidón 5 litros'), ('10L', 'Bidón 10 litros'), ('20L', 'Bidón 20 litros')], max_length=5, null=True)),
                ('tipo_dispensador', models.CharField(blank=True, choices=[('BASICO', 'Dispensador Básico'), ('PREMIUM', 'Dispensador Premium'), ('FRIGORIFICO', 'Dispensador Frigorífico')], max_length=15, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_proxima_entrega', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('PAUSADO', 'Pausado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=10)),
                ('direccion_entrega', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.plan')),
            ],
        ),
    ]
