# Generated by Django 5.0.6 on 2025-06-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_orden_total_orden_buy_order_orden_monto_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion',
            field=models.CharField(default='sin-dirección', max_length=255),
        ),
    ]
